name:
  Fetching AQI data
 
  # Controls when the workflow will run
on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "1 * * * *"
  workflow_dispatch: 
      # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron"
  run-aqi-cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up node js
        uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: run getAQI details
        env: 
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          CPCB_API_KEY: ${{ secrets.CPCB_API_KEY }}
        run: |
          echo "Running get AQI details"
          node cron/aqi.job.js
          
          
        